/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as App02Import } from './routes/app02'
import { Route as App01Import } from './routes/app01'
import { Route as IndexImport } from './routes/index'
import { Route as App02BarImport } from './routes/app02.bar'

// Create/Update Routes

const App02Route = App02Import.update({
  path: '/app02',
  getParentRoute: () => rootRoute,
} as any)

const App01Route = App01Import.update({
  path: '/app01',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const App02BarRoute = App02BarImport.update({
  path: '/bar',
  getParentRoute: () => App02Route,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/app01': {
      preLoaderRoute: typeof App01Import
      parentRoute: typeof rootRoute
    }
    '/app02': {
      preLoaderRoute: typeof App02Import
      parentRoute: typeof rootRoute
    }
    '/app02/bar': {
      preLoaderRoute: typeof App02BarImport
      parentRoute: typeof App02Import
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  App01Route,
  App02Route.addChildren([App02BarRoute]),
])

/* prettier-ignore-end */
